/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestiondematernite;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SnowGirl
 */
public class gerermed extends javax.swing.JFrame {
Connection con=null;
    PreparedStatement pat=null;
    ResultSet ra=null;
    /**
    /**
     * Creates new form gerermed
     */
    public gerermed() {
        initComponents();
          showTableData();
          périmé();
          
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
Image image = new ImageIcon("D:\\5.Etude\\3rd Year Licence\\Projet de fin d'etude\\icones\\hopi2.png").getImage();
setIconImage(image);
//Button Visiblity Here
add_button.setVisible(false);
cancel_button.setVisible(false);
update_button.setVisible(false);
delete_button.setVisible(false);
alert.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InterPanel = new javax.swing.JPanel();
        interLabel = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        adminLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        med_details1 = new javax.swing.JTable();
        Form_Panel = new javax.swing.JPanel();
        qte_label = new javax.swing.JLabel();
        prix_label = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        prix_field = new javax.swing.JTextField();
        dosage_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        dosage_slider = new javax.swing.JSlider();
        qte_spinner = new javax.swing.JSpinner();
        dosage_spinner = new javax.swing.JSpinner();
        qte_slider = new javax.swing.JSlider();
        add_button = new javax.swing.JToggleButton();
        cancel_button = new javax.swing.JToggleButton();
        name_label = new javax.swing.JLabel();
        nom_icon = new javax.swing.JLabel();
        qte_icon = new javax.swing.JLabel();
        price_icon = new javax.swing.JLabel();
        dose_icon = new javax.swing.JLabel();
        date_icon = new javax.swing.JLabel();
        action_label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        combo = new javax.swing.JComboBox<>();
        delete_button = new javax.swing.JToggleButton();
        update_button = new javax.swing.JToggleButton();
        alert = new javax.swing.JLabel();
        qte_min_label = new javax.swing.JLabel();
        qte_icon1 = new javax.swing.JLabel();
        qte_min_slider = new javax.swing.JSlider();
        qte_min_spinner = new javax.swing.JSpinner();
        date_field = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 702));

        InterPanel.setBackground(new java.awt.Color(74, 173, 173));
        InterPanel.setPreferredSize(new java.awt.Dimension(800, 89));

        interLabel.setFont(new java.awt.Font("A Gentle Touch", 1, 36)); // NOI18N
        interLabel.setForeground(new java.awt.Color(255, 255, 255));
        interLabel.setText("Gestion de médicaments");

        logout.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(74, 173, 173));
        logout.setText("Logout");
        logout.setMargin(new java.awt.Insets(2, 5, 2, 5));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InterPanelLayout = new javax.swing.GroupLayout(InterPanel);
        InterPanel.setLayout(InterPanelLayout);
        InterPanelLayout.setHorizontalGroup(
            InterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterPanelLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(interLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        InterPanelLayout.setVerticalGroup(
            InterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interLabel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_30px.png"))); // NOI18N
        jLabel5.setToolTipText("Fermer");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        adminLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pharmacien.png"))); // NOI18N

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));

        med_details1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        med_details1.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        med_details1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom des médicaments", "Quantité", "Dosage", "Prix", "Date de péremption"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        med_details1.setGridColor(new java.awt.Color(255, 255, 255));
        med_details1.setSelectionBackground(new java.awt.Color(0, 119, 135));
        med_details1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med_details1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(med_details1);

        Form_Panel.setBorder(new javax.swing.border.MatteBorder(null));

        qte_label.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        qte_label.setText("Quantité:");

        prix_label.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        prix_label.setText("Prix:");

        name_field.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        name_field.setForeground(new java.awt.Color(0, 51, 51));
        name_field.setText("le nom de médicaments");
        name_field.setToolTipText("");
        name_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                name_fieldFocusGained(evt);
            }
        });
        name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_fieldActionPerformed(evt);
            }
        });

        prix_field.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        prix_field.setForeground(new java.awt.Color(0, 51, 51));
        prix_field.setText("prix en chiffres");
        prix_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prix_fieldFocusGained(evt);
            }
        });
        prix_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prix_fieldActionPerformed(evt);
            }
        });

        dosage_label.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        dosage_label.setText("Dosage:");

        date_label.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        date_label.setText("Date de péremption");

        dosage_slider.setMaximum(1000);
        dosage_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dosage_sliderStateChanged(evt);
            }
        });

        qte_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qte_spinnerStateChanged(evt);
            }
        });

        dosage_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dosage_spinnerStateChanged(evt);
            }
        });

        qte_slider.setMaximum(1000);
        qte_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qte_sliderStateChanged(evt);
            }
        });
        qte_slider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qte_sliderKeyPressed(evt);
            }
        });

        add_button.setBackground(new java.awt.Color(255, 255, 255));
        add_button.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        add_button.setForeground(new java.awt.Color(74, 173, 173));
        add_button.setText("Ajouter");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        cancel_button.setBackground(new java.awt.Color(255, 255, 255));
        cancel_button.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        cancel_button.setForeground(new java.awt.Color(74, 173, 173));
        cancel_button.setText("Annuler");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        name_label.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        name_label.setText("Nom:");

        nom_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Name_Tag_20px.png"))); // NOI18N

        qte_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Purchase_Order_20px.png"))); // NOI18N

        price_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Price_20px.png"))); // NOI18N

        dose_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Dose_20px.png"))); // NOI18N

        date_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expired_20px.png"))); // NOI18N

        action_label.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        action_label.setForeground(new java.awt.Color(74, 173, 173));
        action_label.setText("Choisissez l'action à effectuer:");

        jSeparator1.setForeground(new java.awt.Color(0, 119, 135));

        combo.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supprimer un médicament", "Modifier un médicament", "Ajouter un médicament" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        delete_button.setBackground(new java.awt.Color(255, 255, 255));
        delete_button.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        delete_button.setForeground(new java.awt.Color(74, 173, 173));
        delete_button.setText("Supprimer");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        update_button.setBackground(new java.awt.Color(255, 255, 255));
        update_button.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        update_button.setForeground(new java.awt.Color(74, 173, 173));
        update_button.setText("Modifier");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        alert.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        alert.setForeground(new java.awt.Color(204, 0, 51));
        alert.setText("*Sélectionnez la ligne à modifier dans le tableau suivant ->");

        qte_min_label.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        qte_min_label.setText("Quantité minimale:");

        qte_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Purchase_Order_20px.png"))); // NOI18N

        qte_slider.setMaximum(1000);
        qte_min_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qte_min_sliderStateChanged(evt);
            }
        });
        qte_min_slider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qte_min_sliderKeyPressed(evt);
            }
        });

        qte_min_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qte_min_spinnerStateChanged(evt);
            }
        });

        date_field.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout Form_PanelLayout = new javax.swing.GroupLayout(Form_Panel);
        Form_Panel.setLayout(Form_PanelLayout);
        Form_PanelLayout.setHorizontalGroup(
            Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form_PanelLayout.createSequentialGroup()
                .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Form_PanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(action_label, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addGroup(Form_PanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Form_PanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(alert)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Form_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Form_PanelLayout.createSequentialGroup()
                        .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Form_PanelLayout.createSequentialGroup()
                                .addComponent(nom_icon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name_label))
                            .addGroup(Form_PanelLayout.createSequentialGroup()
                                .addComponent(qte_icon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qte_label)))
                        .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Form_PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qte_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qte_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Form_PanelLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(name_field)
                                .addGap(6, 6, 6))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Form_PanelLayout.createSequentialGroup()
                        .addComponent(dose_icon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dosage_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dosage_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dosage_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Form_PanelLayout.createSequentialGroup()
                        .addComponent(qte_icon1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qte_min_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(qte_min_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qte_min_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Form_PanelLayout.createSequentialGroup()
                        .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Form_PanelLayout.createSequentialGroup()
                                .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Form_PanelLayout.createSequentialGroup()
                                        .addComponent(price_icon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(prix_label))
                                    .addGroup(Form_PanelLayout.createSequentialGroup()
                                        .addComponent(date_icon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(date_label)))
                                .addGap(18, 18, 18)
                                .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Form_PanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(prix_field, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(date_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(Form_PanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancel_button)))
                        .addGap(17, 17, 17))))
            .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Form_PanelLayout.createSequentialGroup()
                    .addContainerGap(182, Short.MAX_VALUE)
                    .addComponent(delete_button)
                    .addGap(128, 128, 128)))
            .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Form_PanelLayout.createSequentialGroup()
                    .addContainerGap(184, Short.MAX_VALUE)
                    .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(129, 129, 129)))
        );
        Form_PanelLayout.setVerticalGroup(
            Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form_PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(action_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alert, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_icon)
                    .addComponent(name_label))
                .addGap(17, 17, 17)
                .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(qte_icon, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(qte_label, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(qte_spinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(qte_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(qte_icon1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(qte_min_label, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(qte_min_spinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(qte_min_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prix_label)
                        .addComponent(prix_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(price_icon))
                .addGap(13, 13, 13)
                .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dosage_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dosage_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dosage_label)
                    .addComponent(dose_icon))
                .addGap(18, 18, 18)
                .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_icon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(date_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date_label)))
                .addGap(30, 30, 30)
                .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_button)
                    .addComponent(cancel_button))
                .addGap(40, 40, 40))
            .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Form_PanelLayout.createSequentialGroup()
                    .addContainerGap(366, Short.MAX_VALUE)
                    .addComponent(delete_button)
                    .addGap(39, 39, 39)))
            .addGroup(Form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Form_PanelLayout.createSequentialGroup()
                    .addContainerGap(365, Short.MAX_VALUE)
                    .addComponent(update_button)
                    .addGap(40, 40, 40)))
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Subtract_30px_1.png"))); // NOI18N
        jLabel15.setToolTipText("Réduire");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Form_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(adminLogo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(adminLogo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Form_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        Toolkit.getDefaultToolkit().beep();
        int confirmed = JOptionPane.showConfirmDialog(null,
            "Êtes-vous sûr de vouloir quitter le programme?", "Message de Confirmation de sortie",
            JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MousePressed
int xy;
    int xx;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }                                    

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {                                      
Object selected = combo.getSelectedItem();
if(selected=="Supprimer un médicament"){
    clear();
    delete_button.setVisible(true);
    cancel_button.setVisible(true);
    add_button.setVisible(false);
    update_button.setVisible(false);
    alert.setVisible(true);
    
}
else if(selected=="Ajouter un médicament"){
    clear();
    delete_button.setVisible(false);
    cancel_button.setVisible(true);
    add_button.setVisible(true);
    update_button.setVisible(false);
    alert.setVisible(false);
    
}
if(selected=="Modifier un médicament"){
    clear();
    delete_button.setVisible(false);
    cancel_button.setVisible(true);
    add_button.setVisible(false);
    update_button.setVisible(true);
    alert.setVisible(true);
    
}
    }                                     

    private void name_fieldActionPerformed(java.awt.event.ActionEvent evt) {                                           
name_field.setText("");
    }                                          

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
         xx = evt.getX();
        xy = evt.getY();
    }
public void clear(){
    name_field.setText("");
    dosage_spinner.setValue(0);
    dosage_slider.setValue(0);
    qte_spinner.setValue(0);
    qte_slider.setValue(0);
    qte_min_spinner.setValue(0);
    qte_min_slider.setValue(0);
    prix_field.setText("");
    
   date_field.setCalendar(null);
}
public void showTableData(){
    try{
        
      con = DriverManager.getConnection("jdbc:mysql://localhost/maternite_med","root","mysql");
      String sql = "SELECT nom, quantité, dosage, prix, date_peremp, quantite_min FROM med";
      pat = con.prepareStatement(sql);
      ra = pat.executeQuery();
      
    med_details1.setModel(DbUtils.resultSetToTableModel(ra));
    MedInsuffisant();
    périmé();
    }
    catch (Exception ex){
          JOptionPane.showMessageDialog(null, ex);
    }
    
}/*
    private void name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_fieldActionPerformed
name_field.setText("");

    }//GEN-LAST:event_name_fieldActionPerformed
*/
    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        try{
              
            String sql="INSERT INTO `med`"
            + "(`nom`, `quantité`, `dosage`,`prix`, `date_peremp`, `quantite_min`)"
            + " VALUES (?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/maternite_med","root","mysql");
            pat = con.prepareStatement(sql);
            pat.setString(1,name_field.getText());
            pat.setInt(2,(int) qte_spinner.getValue());
            pat.setInt(3, (int) dosage_spinner.getValue());
            pat.setString(4,prix_field.getText());
            //Date date = (Date) new SimpleDateFormat("yyyy-MM-dd").setDate(date_field.getDate());
            
        //date_field.setDate(date);
       // java.util.Date jud =  date_field.getDate();
//SimpleDateFormat sdf = new SimpleDateFormat("MMMM dd, yyyy");
//date_field.setDate(sdf.format(jud));
            pat.setObject(5, date_field.getDate());
            pat.setInt(6,(int) qte_min_spinner.getValue());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Le médicament a été ajouté");
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);

        }
        showTableData();
        
        clear();
    }//GEN-LAST:event_add_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        clear();
    }//GEN-LAST:event_cancel_buttonActionPerformed
/*
    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        Object selected = combo.getSelectedItem();
        if(selected=="Supprimer un médicament"){
            delete_button.setVisible(true);
            cancel_button.setVisible(true);
            add_button.setVisible(false);
            update_button.setVisible(false);

        }
        else if(selected=="Ajouter un médicament"){
            delete_button.setVisible(false);
            cancel_button.setVisible(true);
            add_button.setVisible(true);
            update_button.setVisible(false);

        }
        if(selected=="Modifier un médicament"){
            delete_button.setVisible(false);
            cancel_button.setVisible(true);
            add_button.setVisible(false);
            update_button.setVisible(true);

        }
    }//GEN-LAST:event_comboActionPerformed
*/
    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        try{
            
            String sql="DELETE FROM med WHERE nom =?";

            con = DriverManager.getConnection("jdbc:mysql://localhost/maternite_med","root","mysql");
            pat = con.prepareStatement(sql);
            pat.setString(1,name_field.getText());

            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Le médicament a été supprimé!");
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);

        }
        showTableData();
        
        clear();
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        try{
             

            String sql="UPDATE med SET nom=?,quantité=?,dosage=?,prix=?,date_peremp=?,quantite_min=? WHERE nom=?";

            con = DriverManager.getConnection("jdbc:mysql://localhost/maternite_med","root","mysql");
            pat = con.prepareStatement(sql);

            pat.setString(1,name_field.getText());
            pat.setInt(2, (int) qte_spinner.getValue());
            pat.setInt(6, (int) qte_min_spinner.getValue());
            pat.setInt(3, (int) dosage_spinner.getValue());
            pat.setString(4,prix_field.getText());
             
            pat.setObject(5, date_field.getDate());
            pat.setString(7,name_field.getText());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Le médicament a été modifié!");

        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);

        }
        clear();
        showTableData();
   
    }//GEN-LAST:event_update_buttonActionPerformed

    private void qte_sliderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qte_sliderKeyPressed

qte_spinner.setValue((int) qte_slider.getValue());
    }//GEN-LAST:event_qte_sliderKeyPressed

    private void qte_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qte_sliderStateChanged
qte_spinner.setValue((int) qte_slider.getValue());
    }//GEN-LAST:event_qte_sliderStateChanged

    private void dosage_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dosage_sliderStateChanged
dosage_spinner.setValue((int) dosage_slider.getValue());    }//GEN-LAST:event_dosage_sliderStateChanged

    private void qte_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qte_spinnerStateChanged
qte_slider.setValue((int) qte_spinner.getValue());    }//GEN-LAST:event_qte_spinnerStateChanged

    private void dosage_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dosage_spinnerStateChanged
dosage_slider.setValue((int) dosage_spinner.getValue());
    }//GEN-LAST:event_dosage_spinnerStateChanged

    private void prix_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prix_fieldActionPerformed
prix_field.setText("");
    }//GEN-LAST:event_prix_fieldActionPerformed

    private void name_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_fieldFocusGained
name_field.setText("");
    }//GEN-LAST:event_name_fieldFocusGained

    private void prix_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prix_fieldFocusGained
prix_field.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_prix_fieldFocusGained

    private void med_details1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med_details1MouseClicked
   
        DefaultTableModel model = (DefaultTableModel) med_details1.getModel();
        int index = med_details1.getSelectedRow();
        name_field.setText(model.getValueAt(index,0).toString());
        qte_spinner.setValue(model.getValueAt(index,1));
        dosage_spinner.setValue(model.getValueAt(index,2));
        qte_slider.setValue((int) model.getValueAt(index,1));
        dosage_slider.setValue((int) model.getValueAt(index,2));
        prix_field.setText(model.getValueAt(index,3).toString());
        //Date date = (Date) new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(index,4));
        date_field.setDate((java.util.Date) model.getValueAt(index,4));
        qte_min_slider.setValue((int) model.getValueAt(index,5));
        qte_min_spinner.setValue(model.getValueAt(index,5));
    }//GEN-LAST:event_med_details1MouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
Toolkit.getDefaultToolkit().beep();
        int confirmed = JOptionPane.showConfirmDialog(null,
            "Êtes-vous sûr de vouloir quitter le programme?", "Message de Confirmation de sortie",
            JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
        }      // TODO add your handling code here
    }//GEN-LAST:event_logoutActionPerformed

    private void qte_min_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qte_min_sliderStateChanged
qte_min_spinner.setValue((int) qte_min_slider.getValue());

    }//GEN-LAST:event_qte_min_sliderStateChanged

    private void qte_min_sliderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qte_min_sliderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_qte_min_sliderKeyPressed

    private void qte_min_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qte_min_spinnerStateChanged
qte_min_slider.setValue((int) qte_min_spinner.getValue());
    }//GEN-LAST:event_qte_min_spinnerStateChanged

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        setExtendedState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel15MousePressed
private void périmé()
{
    String warningMsg="";
try
{
    
	Calendar cal = Calendar.getInstance();
   con = DriverManager.getConnection("jdbc:mysql://localhost/maternite_med","root","mysql");
      String sql = "SELECT nom, date_peremp FROM med";
      pat = con.prepareStatement(sql);
      ra = pat.executeQuery();
      while (ra.next()) {
    Date datePeremp = ra.getDate("date_peremp");
    //Date date3=(Date) datePeremp;
    String nom = ra.getString("nom");
if(  (cal.getTime()).after(datePeremp))
    {
        warningMsg += " "+nom+";";
    }
    
      }
     Toolkit.getDefaultToolkit().beep();
     JOptionPane.showMessageDialog(this, "Medicament(s) périmé(s):"+warningMsg, "Dialogue",
        JOptionPane.ERROR_MESSAGE);
    }
    catch (Exception ex){
          JOptionPane.showMessageDialog(null, ex);
    }

}
        private void MedInsuffisant()
{
    
     try{
        
      con = DriverManager.getConnection("jdbc:mysql://localhost/maternite_med","root","mysql");
      String sql = "SELECT nom, quantité, quantite_min FROM med";
      pat = con.prepareStatement(sql);
      ra = pat.executeQuery();
      while (ra.next()) {
    int qte = ra.getInt("quantité");
    int qte_min = ra.getInt("quantite_min");
    String nom = ra.getString("nom");
    if(qte<=qte_min)
    {
        Toolkit.getDefaultToolkit().beep();
        String warningMsg = "La quantité du "+nom+" est insuffisante!";
        JOptionPane.showMessageDialog(this, warningMsg, "Dialogue",
        JOptionPane.ERROR_MESSAGE);
         
    }
    
      }
    }
    catch (Exception ex){
          JOptionPane.showMessageDialog(null, ex);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gerermed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gerermed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gerermed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gerermed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gerermed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Form_Panel;
    private javax.swing.JPanel InterPanel;
    private javax.swing.JLabel action_label;
    private javax.swing.JToggleButton add_button;
    private javax.swing.JLabel adminLogo;
    private javax.swing.JLabel alert;
    private javax.swing.JToggleButton cancel_button;
    private javax.swing.JComboBox<String> combo;
    private com.toedter.calendar.JDateChooser date_field;
    private javax.swing.JLabel date_icon;
    private javax.swing.JLabel date_label;
    private javax.swing.JToggleButton delete_button;
    private javax.swing.JLabel dosage_label;
    private javax.swing.JSlider dosage_slider;
    private javax.swing.JSpinner dosage_spinner;
    private javax.swing.JLabel dose_icon;
    private javax.swing.JLabel interLabel;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logout;
    private javax.swing.JTable med_details1;
    private javax.swing.JTextField name_field;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel nom_icon;
    private javax.swing.JLabel price_icon;
    private javax.swing.JTextField prix_field;
    private javax.swing.JLabel prix_label;
    private javax.swing.JLabel qte_icon;
    private javax.swing.JLabel qte_icon1;
    private javax.swing.JLabel qte_label;
    private javax.swing.JLabel qte_min_label;
    private javax.swing.JSlider qte_min_slider;
    private javax.swing.JSpinner qte_min_spinner;
    private javax.swing.JSlider qte_slider;
    private javax.swing.JSpinner qte_spinner;
    private javax.swing.JToggleButton update_button;
    // End of variables declaration//GEN-END:variables
}
