/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestiondematernite;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SnowGirl
 */
public class interfacedoc extends javax.swing.JFrame {
Connection con=null;
    PreparedStatement pat=null;
    ResultSet ra=null;
    Statement st;
    
    /** Creates new form interfacedoc */
    public interfacedoc() {
        initComponents();
        combo_doc();
        combo_sf();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
          setTitle("Gestion de Maternié: Interface d'Administrateur");
        Image image = new ImageIcon("D:\\5.Etude\\3rd Year Licence\\Projet de fin d'etude\\icones\\hopi2.png").getImage();
setIconImage(image);
MenuChoose.setVisible(false);
  showTableData();
  showTableData2();
  // combo box
   
 /* try{
      con = DriverManager.getConnection("jdbc:mysql://localhost/maternite_profile","root","");
      st = con.createStatement();
      String s = "select Nom from doctor";
      ra = st.executeQuery(s);
        while(ra.next())
        {
            doc.addItem(ra.getString(1));
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "ERROR");
    }finally{
        try{
            st.close();
            ra.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "ERROR CLOSE");
        }*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adminLogo = new javax.swing.JLabel();
        InterPanel = new javax.swing.JPanel();
        interLabel = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MenuChoose = new javax.swing.JTabbedPane();
        list_pane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patient_details = new javax.swing.JTable();
        new_pane = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lieu = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hist = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        adresse = new javax.swing.JTextArea();
        gs = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        urgence = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        daten = new com.toedter.calendar.JDateChooser();
        doc = new javax.swing.JComboBox<>();
        sf = new javax.swing.JComboBox<>();
        search_pane = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        code2 = new javax.swing.JTextField();
        search_panel = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        reset_panel = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        patient_details1 = new javax.swing.JTable();
        side = new javax.swing.JPanel();
        interLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DocBut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ind_doc = new javax.swing.JPanel();
        nurseBut = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ind_nurse = new javax.swing.JPanel();
        chefBut = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ind_chef = new javax.swing.JPanel();
        receptBut = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ind_recept = new javax.swing.JPanel();
        patientBut = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ind_pati = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(723, 234));

        adminLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/docc.png"))); // NOI18N

        InterPanel.setBackground(new java.awt.Color(41, 39, 40));
        InterPanel.setPreferredSize(new java.awt.Dimension(800, 89));

        interLabel.setFont(new java.awt.Font("A Gentle Touch", 1, 36)); // NOI18N
        interLabel.setForeground(new java.awt.Color(255, 255, 255));
        interLabel.setText("Interface Docteur");

        logout.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 51, 51));
        logout.setText("Logout");
        logout.setMargin(new java.awt.Insets(2, 5, 2, 5));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InterPanelLayout = new javax.swing.GroupLayout(InterPanel);
        InterPanel.setLayout(InterPanelLayout);
        InterPanelLayout.setHorizontalGroup(
            InterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(interLabel)
                .addGap(81, 81, 81)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        InterPanelLayout.setVerticalGroup(
            InterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(InterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interLabel)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Subtract_30px_2.png"))); // NOI18N
        jLabel15.setToolTipText("Réduire");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_30px_4.png"))); // NOI18N
        jLabel5.setToolTipText("Fermer");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        MenuChoose.setBackground(new java.awt.Color(204, 204, 0));
        MenuChoose.setForeground(new java.awt.Color(41, 39, 40));
        MenuChoose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuChoose.setFont(new java.awt.Font("Tekton Pro", 1, 16));
        MenuChoose.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MenuChooseStateChanged(evt);
            }
        });

        patient_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Nom", "Prenom", "Date De Naissance", "Telephone", "Email", "Contact d'urgence", "Groupe Sanguin", "Historique Médical", "SageFemme du cas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patient_details);

        javax.swing.GroupLayout list_paneLayout = new javax.swing.GroupLayout(list_pane);
        list_pane.setLayout(list_paneLayout);
        list_paneLayout.setHorizontalGroup(
            list_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        list_paneLayout.setVerticalGroup(
            list_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        MenuChoose.addTab("Liste des patientes", list_pane);

        jLabel17.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(41, 39, 40));
        jLabel17.setText("Code:");

        jLabel18.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(41, 39, 40));
        jLabel18.setText("Nom:");

        jLabel19.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(41, 39, 40));
        jLabel19.setText("Prenom:");

        code.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        code.setToolTipText("Code de patiente");
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });

        nom.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        nom.setToolTipText("Nom de patiente");

        prenom.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        prenom.setToolTipText("Prénom de patiente");

        jLabel20.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(41, 39, 40));
        jLabel20.setText("Date Naiss:");

        jLabel21.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(41, 39, 40));
        jLabel21.setText("Lieu Naiss:");

        jLabel22.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(41, 39, 40));
        jLabel22.setText("Email:");
        jLabel22.setToolTipText("Assurance");

        lieu.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        lieu.setToolTipText("Tel de patiente");

        email.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        email.setToolTipText("Prénom de patiente");

        jLabel23.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(41, 39, 40));
        jLabel23.setText("Telephone:");
        jLabel23.setToolTipText("Tel de marie/fixe");

        tel.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        tel.setToolTipText("Nom de patiente");

        jLabel24.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(41, 39, 40));
        jLabel24.setText("Remarques:");

        hist.setColumns(20);
        hist.setRows(5);
        hist.setToolTipText("Remarques importantes");
        hist.setWrapStyleWord(true);
        jScrollPane3.setViewportView(hist);

        jButton1.setBackground(new java.awt.Color(41, 39, 40));
        jButton1.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(41, 39, 40));
        jButton2.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Annuler");

        jLabel25.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 0, 51));
        jLabel25.setText("*");

        jLabel26.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 0, 51));
        jLabel26.setText("*");

        jLabel27.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 0, 51));
        jLabel27.setText("*");

        jLabel28.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 0, 51));
        jLabel28.setText("*");

        jLabel31.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 0, 51));
        jLabel31.setText("*");

        jLabel29.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(41, 39, 40));
        jLabel29.setText("Adresse:");

        adresse.setColumns(20);
        adresse.setRows(5);
        jScrollPane2.setViewportView(adresse);

        gs.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        gs.setToolTipText("Prénom de patiente");

        jLabel33.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(41, 39, 40));
        jLabel33.setText("Groupe_Sanguin");
        jLabel33.setToolTipText("Assurance");

        urgence.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        urgence.setToolTipText("Prénom de patiente");

        jLabel36.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(41, 39, 40));
        jLabel36.setText("Contact d'urgence:");
        jLabel36.setToolTipText("Assurance");

        jLabel37.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(41, 39, 40));
        jLabel37.setText("Sage-femme");
        jLabel37.setToolTipText("Assurance");

        jLabel38.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(41, 39, 40));
        jLabel38.setText("Médecin");
        jLabel38.setToolTipText("Assurance");

        /*
        doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        */

        /*
        */

        javax.swing.GroupLayout new_paneLayout = new javax.swing.GroupLayout(new_pane);
        new_pane.setLayout(new_paneLayout);
        new_paneLayout.setHorizontalGroup(
            new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_paneLayout.createSequentialGroup()
                .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(new_paneLayout.createSequentialGroup()
                        .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(new_paneLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26))
                            .addGroup(new_paneLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25))
                            .addGroup(new_paneLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27))
                            .addGroup(new_paneLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28))
                            .addComponent(jLabel21)
                            .addComponent(jLabel29)
                            .addGroup(new_paneLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31))
                            .addComponent(jLabel22)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(urgence)
                            .addComponent(code, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prenom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lieu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(tel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email)
                            .addComponent(daten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(new_paneLayout.createSequentialGroup()
                                .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38))
                                .addGap(33, 33, 33)
                                .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(new_paneLayout.createSequentialGroup()
                                .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(gs)))))
                    .addGroup(new_paneLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(206, 206, 206)))
                .addContainerGap())
        );
        new_paneLayout.setVerticalGroup(
            new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_paneLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel26))
                .addGap(13, 13, 13)
                .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(172, 172, 172))
            .addGroup(new_paneLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(new_paneLayout.createSequentialGroup()
                        .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(daten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(lieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(new_paneLayout.createSequentialGroup()
                        .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(sf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(urgence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(new_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        MenuChoose.addTab("Nouvelle Patiente", new_pane);

        search_pane.setForeground(new java.awt.Color(41, 39, 40));
        search_pane.setPreferredSize(new java.awt.Dimension(700, 411));

        jLabel11.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(41, 39, 40));
        jLabel11.setText("Code:");

        code2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        code2.setToolTipText("Code de patiente");

        search_panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                search_panelMousePressed(evt);
            }
        });

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_25px.png"))); // NOI18N

        jLabel34.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(41, 39, 40));
        jLabel34.setText("Rechercher");

        javax.swing.GroupLayout search_panelLayout = new javax.swing.GroupLayout(search_panel);
        search_panel.setLayout(search_panelLayout);
        search_panelLayout.setHorizontalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addContainerGap())
        );
        search_panelLayout.setVerticalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        reset_panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reset_panelMousePressed(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Reset_25px.png"))); // NOI18N

        jLabel32.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(41, 39, 40));
        jLabel32.setText("Annuler");

        javax.swing.GroupLayout reset_panelLayout = new javax.swing.GroupLayout(reset_panel);
        reset_panel.setLayout(reset_panelLayout);
        reset_panelLayout.setHorizontalGroup(
            reset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reset_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        reset_panelLayout.setVerticalGroup(
            reset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reset_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel30))
                .addContainerGap())
        );

        patient_details1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Nom", "Prenom", "Date De Naissance", "Telephone", "Email", "Contact d'urgence", "Groupe Sanguin", "Historique Médical", "SageFemme du cas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(patient_details1);

        javax.swing.GroupLayout search_paneLayout = new javax.swing.GroupLayout(search_pane);
        search_pane.setLayout(search_paneLayout);
        search_paneLayout.setHorizontalGroup(
            search_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(search_paneLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(search_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(search_paneLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(61, 61, 61)
                        .addComponent(code2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(search_paneLayout.createSequentialGroup()
                        .addComponent(search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reset_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        search_paneLayout.setVerticalGroup(
            search_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_paneLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(search_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(code2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(search_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        MenuChoose.addTab("Rechercher Patiente", search_pane);

        MenuChoose.setIconAt(0, new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_List_20px.png")));
        MenuChoose.setIconAt(1, new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_New_Contact_20px.png")));
        MenuChoose.setIconAt(2, new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_20px.png")));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(adminLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(InterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(MenuChoose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(adminLogo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuChoose)
                .addContainerGap())
        );

        side.setBackground(new java.awt.Color(41, 39, 40));

        interLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        interLabel1.setForeground(new java.awt.Color(255, 255, 255));
        interLabel1.setText("Operations");

        DocBut.setBackground(new java.awt.Color(41, 39, 40));
        DocBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DocBut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DocButFocusGained(evt);
            }
        });
        DocBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DocButMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Liste des Patientes");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Schedule_20px.png"))); // NOI18N

        ind_doc.setBackground(new java.awt.Color(250, 250, 250));
        ind_doc.setOpaque(false);

        javax.swing.GroupLayout ind_docLayout = new javax.swing.GroupLayout(ind_doc);
        ind_doc.setLayout(ind_docLayout);
        ind_docLayout.setHorizontalGroup(
            ind_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_docLayout.setVerticalGroup(
            ind_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DocButLayout = new javax.swing.GroupLayout(DocBut);
        DocBut.setLayout(DocButLayout);
        DocButLayout.setHorizontalGroup(
            DocButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocButLayout.createSequentialGroup()
                .addComponent(ind_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DocButLayout.setVerticalGroup(
            DocButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(DocButLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DocButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)))
        );

        nurseBut.setBackground(new java.awt.Color(41, 39, 40));
        nurseBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nurseBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nurseButMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fiche médicale des patientes");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Diff_Files_20px.png"))); // NOI18N

        ind_nurse.setBackground(new java.awt.Color(250, 250, 250));
        ind_nurse.setOpaque(false);
        ind_nurse.setPreferredSize(new java.awt.Dimension(4, 43));

        javax.swing.GroupLayout ind_nurseLayout = new javax.swing.GroupLayout(ind_nurse);
        ind_nurse.setLayout(ind_nurseLayout);
        ind_nurseLayout.setHorizontalGroup(
            ind_nurseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_nurseLayout.setVerticalGroup(
            ind_nurseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout nurseButLayout = new javax.swing.GroupLayout(nurseBut);
        nurseBut.setLayout(nurseButLayout);
        nurseButLayout.setHorizontalGroup(
            nurseButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nurseButLayout.createSequentialGroup()
                .addComponent(ind_nurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        nurseButLayout.setVerticalGroup(
            nurseButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_nurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(nurseButLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nurseButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)))
        );

        chefBut.setBackground(new java.awt.Color(41, 39, 40));
        chefBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chefButMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nouvelle Patiente");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Print_20px.png"))); // NOI18N

        ind_chef.setBackground(new java.awt.Color(250, 250, 250));
        ind_chef.setOpaque(false);
        ind_chef.setPreferredSize(new java.awt.Dimension(4, 43));

        javax.swing.GroupLayout ind_chefLayout = new javax.swing.GroupLayout(ind_chef);
        ind_chef.setLayout(ind_chefLayout);
        ind_chefLayout.setHorizontalGroup(
            ind_chefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_chefLayout.setVerticalGroup(
            ind_chefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout chefButLayout = new javax.swing.GroupLayout(chefBut);
        chefBut.setLayout(chefButLayout);
        chefButLayout.setHorizontalGroup(
            chefButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chefButLayout.createSequentialGroup()
                .addComponent(ind_chef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        chefButLayout.setVerticalGroup(
            chefButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_chef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(chefButLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chefButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)))
        );

        receptBut.setBackground(new java.awt.Color(41, 39, 40));
        receptBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                receptButMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Rechercher patientes");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Pregnant_25px.png"))); // NOI18N

        ind_recept.setBackground(new java.awt.Color(250, 250, 250));
        ind_recept.setOpaque(false);
        ind_recept.setPreferredSize(new java.awt.Dimension(4, 43));

        javax.swing.GroupLayout ind_receptLayout = new javax.swing.GroupLayout(ind_recept);
        ind_recept.setLayout(ind_receptLayout);
        ind_receptLayout.setHorizontalGroup(
            ind_receptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_receptLayout.setVerticalGroup(
            ind_receptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout receptButLayout = new javax.swing.GroupLayout(receptBut);
        receptBut.setLayout(receptButLayout);
        receptButLayout.setHorizontalGroup(
            receptButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receptButLayout.createSequentialGroup()
                .addComponent(ind_recept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        receptButLayout.setVerticalGroup(
            receptButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_recept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(receptButLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(receptButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)))
        );

        patientBut.setBackground(new java.awt.Color(41, 39, 40));
        patientBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                patientButMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Consulter l'horaire");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Calendar_20px.png"))); // NOI18N

        ind_pati.setBackground(new java.awt.Color(250, 250, 250));
        ind_pati.setOpaque(false);
        ind_pati.setPreferredSize(new java.awt.Dimension(4, 43));

        javax.swing.GroupLayout ind_patiLayout = new javax.swing.GroupLayout(ind_pati);
        ind_pati.setLayout(ind_patiLayout);
        ind_patiLayout.setHorizontalGroup(
            ind_patiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_patiLayout.setVerticalGroup(
            ind_patiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout patientButLayout = new javax.swing.GroupLayout(patientBut);
        patientBut.setLayout(patientButLayout);
        patientButLayout.setHorizontalGroup(
            patientButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientButLayout.createSequentialGroup()
                .addComponent(ind_pati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        patientButLayout.setVerticalGroup(
            patientButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_pati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(patientButLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hospital_icon-icons.com_76234.png"))); // NOI18N

        javax.swing.GroupLayout sideLayout = new javax.swing.GroupLayout(side);
        side.setLayout(sideLayout);
        sideLayout.setHorizontalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DocBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chefBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(receptBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(patientBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sideLayout.createSequentialGroup()
                .addGroup(sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(interLabel1))
                    .addGroup(sideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addComponent(nurseBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideLayout.setVerticalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(interLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(DocBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nurseBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chefBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receptBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(side, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        // Code adding the component to the parent container - not shown here

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Toolkit.getDefaultToolkit().beep();
        int confirmed = JOptionPane.showConfirmDialog(null,
            "Êtes-vous sûr de vouloir quitter le programme?", "Message de Confirmation de sortie",
            JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
        }       // TODO add your handling code here
    }//GEN-LAST:event_logoutActionPerformed

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        setExtendedState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel15MousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        Toolkit.getDefaultToolkit().beep();
        int confirmed = JOptionPane.showConfirmDialog(null,
            "Êtes-vous sûr de vouloir quitter le programme?", "Message de Confirmation de sortie",
            JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MousePressed

    private void DocButFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DocButFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DocButFocusGained

    private void DocButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DocButMousePressed
    MenuChoose.setSelectedIndex(0);
           MenuChoose.setVisible(true);
            
     setColor(DocBut);
        resetColor(chefBut);
        resetColor(patientBut);
        resetColor(nurseBut);
        resetColor(receptBut);

        //resetColor(ind_doc);
        //indices
        ind_pati.setOpaque(false);
        ind_doc.setOpaque(true);
        ind_nurse.setOpaque(false);
        ind_chef.setOpaque(false);
        ind_recept.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14));

        //panels

    }//GEN-LAST:event_DocButMousePressed

    private void nurseButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nurseButMousePressed
        MenuChoose.setVisible(false);
//font
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14));

        //indices
        ind_pati.setOpaque(false);
        ind_doc.setOpaque(false);
        ind_nurse.setOpaque(true);
        ind_chef.setOpaque(false);
        ind_recept.setOpaque(false);

        //couleur
        setColor(nurseBut);
        resetColor(chefBut);
        resetColor(patientBut);
        resetColor(DocBut);

        //resetColor(ind_nurse);
    }//GEN-LAST:event_nurseButMousePressed

    private void chefButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chefButMousePressed
        MenuChoose.setSelectedIndex(1);
           MenuChoose.setVisible(true);
           setColor(chefBut);
        resetColor(DocBut);
        resetColor(patientBut);
        resetColor(nurseBut);
        resetColor(receptBut);

        //INdice
        ind_pati.setOpaque(false);
        ind_doc.setOpaque(false);
        ind_nurse.setOpaque(false);
        ind_chef.setOpaque(true);
        ind_recept.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14));

    }//GEN-LAST:event_chefButMousePressed

    private void receptButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receptButMousePressed
     
      MenuChoose.setSelectedIndex(2);
           MenuChoose.setVisible(true);
           setColor(receptBut);
        resetColor(chefBut);
        resetColor(patientBut);
        resetColor(nurseBut);
        resetColor(DocBut);

        // indices
        ind_pati.setOpaque(false);
        ind_doc.setOpaque(false);
        ind_nurse.setOpaque(false);
        ind_chef.setOpaque(false);
        ind_recept.setOpaque(true);

        //Font
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14));

        //panels

    }//GEN-LAST:event_receptButMousePressed

    private void patientButMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientButMousePressed
MenuChoose.setVisible(false);
setColor(patientBut);
        resetColor(chefBut);
        resetColor(DocBut);
        resetColor(nurseBut);
        resetColor(receptBut);

        //Indices
        ind_pati.setOpaque(true);
        ind_doc.setOpaque(false);
        ind_nurse.setOpaque(false);
        ind_chef.setOpaque(false);
        ind_recept.setOpaque(false);

        //font

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16));
        // panels

    }//GEN-LAST:event_patientButMousePressed

    private void MenuChooseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MenuChooseStateChanged
        int index = MenuChoose.getSelectedIndex();
        if(index==0){
               
            
     setColor(DocBut);
        resetColor(chefBut);
        resetColor(patientBut);
        resetColor(nurseBut);
        resetColor(receptBut);

        //resetColor(ind_doc);
        //indices
        ind_pati.setOpaque(false);
        ind_doc.setOpaque(true);
        ind_nurse.setOpaque(false);
        ind_chef.setOpaque(false);
        ind_recept.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14));

        
            }
        else if (index==1){
                 setColor(chefBut);
        resetColor(DocBut);
        resetColor(patientBut);
        resetColor(nurseBut);
        resetColor(receptBut);

        //INdice
        ind_pati.setOpaque(false);
        ind_doc.setOpaque(false);
        ind_nurse.setOpaque(false);
        ind_chef.setOpaque(true);
        ind_recept.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14));
            }
        else if(index==2){
                 setColor(receptBut);
        resetColor(chefBut);
        resetColor(patientBut);
        resetColor(nurseBut);
        resetColor(DocBut);

        // indices
        ind_pati.setOpaque(false);
        ind_doc.setOpaque(false);
        ind_nurse.setOpaque(false);
        ind_chef.setOpaque(false);
        ind_recept.setOpaque(true);

        //Font
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14));

            }
        
        
    }//GEN-LAST:event_MenuChooseStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try{
            String sql="INSERT INTO `patientDetails`"
            + "(`Code`, `Nom`,`Prenom`, `Date_naissance`, `tel`, `email`,  `Contact_Urgence`, `groupe_sanguin`,`Historique_Médical`, `SF_du_cas`,`Lieu_naissance`,`Adresse`,`Médecin_du_cas`)"
            + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/maternite_profile","root","mysql");
            pat = con.prepareStatement(sql);
            pat.setString(1,code.getText());
            pat.setString(2,nom.getText());
            pat.setString(3,prenom.getText());
            pat.setObject(4,daten.getDate());
            pat.setString(5,tel.getText());
            pat.setString(6,email.getText());
            pat.setString(7,urgence.getText());
            pat.setString(8,gs.getText());
            pat.setString(9,hist.getText());
            pat.setString(10,(String) sf.getSelectedItem());
            pat.setString(11,lieu.getText());
            pat.setString(12,adresse.getText());
            pat.setString(13, (String) doc.getSelectedItem());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null, "La patiente a été ajoutée");
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);

        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void search_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_panelMousePressed
      showTableDataSpecial();
    }//GEN-LAST:event_search_panelMousePressed

    private void reset_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_panelMousePressed
code2.setText("");
    }//GEN-LAST:event_reset_panelMousePressed
void setColor(JPanel pane){
        pane.setBackground(new Color(204,204,204));
    }
    
    void resetColor(JPanel pane)
    {
        pane.setBackground(new Color(41,39,40));
    }
    
public void showTableData2(){
    try{
        
      con = DriverManager.getConnection("jdbc:mysql://localhost/maternite_patient","root","mysql");
      String sql = "SELECT Code, Nom, Prenom, Date_naissance, tel, email, Contact_Urgence, groupe_sanguin, Historique_Médical, SF_du_cas FROM patientDetails";
      pat = con.prepareStatement(sql);
      ra = pat.executeQuery();
      patient_details1.setModel(DbUtils.resultSetToTableModel(ra));
    
    
    
    }
    catch (Exception ex){
          JOptionPane.showMessageDialog(null, ex);
    }
    
}
public void showTableData(){
    try{
        
      con = DriverManager.getConnection("jdbc:mysql://localhost/maternite_patient","root","mysql");
      String sql = "SELECT Code, Nom, Prenom, Date_naissance, tel, email, Contact_Urgence, groupe_sanguin, Historique_Médical, SF_du_cas FROM patientDetails";
      pat = con.prepareStatement(sql);
      ra = pat.executeQuery();
      patient_details1.setModel(DbUtils.resultSetToTableModel(ra));
    patient_details.setModel(DbUtils.resultSetToTableModel(ra));
    
    
    }
    catch (Exception ex){
          JOptionPane.showMessageDialog(null, ex);
    }
    
}
public void showTableDataSpecial(){
    try{
         if(code2.getText().equals(""))
        {
             JOptionPane.showMessageDialog(null, "Veuillez saisir le code S'il vous plaît!");
        }
         else{
      con = DriverManager.getConnection("jdbc:mysql://localhost/maternite_patient","root","mysql");
      String sql = "SELECT * FROM patientDetails where Code=?";
      pat = con.prepareStatement(sql);
      pat.setString(1,code2.getText());
           
                  
           ra = pat.executeQuery();
    patient_details1.setModel(DbUtils.resultSetToTableModel(ra));
         }
    }
    catch (Exception ex){
          JOptionPane.showMessageDialog(null, ex);
    }
}
  /*  private void patient_detailsMouseClicked(java.awt.event.MouseEvent evt) {                                          
   
        DefaultTableModel model = (DefaultTableModel) patient_details.getModel();
        int index = patient_details.getSelectedRow();
        name_field.setText(model.getValueAt(index,0).toString());
        qte_spinner.setValue(model.getValueAt(index,1));
        dosage_spinner.setValue(model.getValueAt(index,2));
        qte_slider.setValue((int) model.getValueAt(index,1));
        dosage_slider.setValue((int) model.getValueAt(index,2));
        prix_field.setText(model.getValueAt(index,3).toString());
        //Date date = (Date) new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(index,4));
        date_field.setDate((java.util.Date) model.getValueAt(index,4));
        qte_min_slider.setValue((int) model.getValueAt(index,5));
        qte_min_spinner.setValue(model.getValueAt(index,5));
    }                                         
*/
public void combo_doc(){
    try{
      con = DriverManager.getConnection("jdbc:mysql://localhost/maternite_profile","root","");
      st = con.createStatement();
      String s = "select Nom from doctor";
      ra = st.executeQuery(s);
        while(ra.next())
        {
            doc.addItem(ra.getString(1));
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "ERROR");
    }}

public void combo_sf(){
    try{
      con = DriverManager.getConnection("jdbc:mysql://localhost/maternite_profile","root","");
      st = con.createStatement();
      String s = "select Nom from nurse";
      ra = st.executeQuery(s);
        while(ra.next())
        {
            doc.addItem(ra.getString(1));
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "ERROR");
    }}

    int xy;
    int xx;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }                                    

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
         xx = evt.getX();
        xy = evt.getY();
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfacedoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfacedoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfacedoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfacedoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfacedoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DocBut;
    private javax.swing.JPanel InterPanel;
    private javax.swing.JTabbedPane MenuChoose;
    private javax.swing.JLabel adminLogo;
    private javax.swing.JTextArea adresse;
    private javax.swing.JPanel chefBut;
    private javax.swing.JTextField code;
    private javax.swing.JTextField code2;
    private com.toedter.calendar.JDateChooser daten;
    private javax.swing.JComboBox<String> doc;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gs;
    private javax.swing.JTextArea hist;
    private javax.swing.JPanel ind_chef;
    private javax.swing.JPanel ind_doc;
    private javax.swing.JPanel ind_nurse;
    private javax.swing.JPanel ind_pati;
    private javax.swing.JPanel ind_recept;
    private javax.swing.JLabel interLabel;
    private javax.swing.JLabel interLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lieu;
    private javax.swing.JPanel list_pane;
    private javax.swing.JButton logout;
    private javax.swing.JPanel new_pane;
    private javax.swing.JTextField nom;
    private javax.swing.JPanel nurseBut;
    private javax.swing.JPanel patientBut;
    private javax.swing.JTable patient_details;
    private javax.swing.JTable patient_details1;
    private javax.swing.JTextField prenom;
    private javax.swing.JPanel receptBut;
    private javax.swing.JPanel reset_panel;
    private javax.swing.JPanel search_pane;
    private javax.swing.JPanel search_panel;
    private javax.swing.JComboBox<String> sf;
    private javax.swing.JPanel side;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField urgence;
    // End of variables declaration//GEN-END:variables

}
